[package]
name = "rust-bevy-rogue"
version = "0.15.0"
edition = "2021"

[profile.dev]
opt-level = 1

[dependencies]
bevy =  "0.15"
bevy_egui = "0.31"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

rand = "0.8.5"
petgraph = "0.6"